CXX=g++
CXXFLAGS=-g3 -O3 -msse3 
LDLIBS= -ltjutils -lodindata -lodinpara -lodinseq -ltjutils -lblitz -lgsl 
PROGS= MAP 
  

all: $(PROGS)




clean:
	rm -f $(PROGS)

#g++ MAP.cpp -O3 -o MAP -lfreki -lblitz -lgsl -lblas

