######################################################################
# Automatically generated by qmake (1.07a) Tue Oct 27 09:11:52 2009
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
SOURCES += slider.cpp
