CXX=g++
CXXFLAGS=-g3 -O3 -msse3 
LDLIBS= -ltjutils -lodindata -lodinpara -lodinseq -ltjutils -lblitz -lgsl 
PROGS= GM_MASK
# -ltjutils
PROGS= CORREL_w_1dim


 

all: $(PROGS)




clean:
	rm -f $(PROGS)
