######################################################################
# Automatically generated by qmake (1.07a) Tue Oct 27 12:36:20 2009
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
SOURCES += main.cpp
