######################################################################
# Automatically generated by qmake (1.07a) Tue Mar 24 15:24:22 2009
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
SOURCES += zeichner.cpp
