######################################################################
# Automatically generated by qmake (1.07a) Mon Oct 26 18:42:08 2009
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
SOURCES += font.cpp
