######################################################################
# Automatically generated by qmake (1.07a) Mon Oct 26 18:20:11 2009
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
SOURCES += main.cpp
