######################################################################
# Automatically generated by qmake (1.07a) Mon Oct 26 18:20:35 2009
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
SOURCES += Hello.cpp
