######################################################################
# Automatically generated by qmake (1.07a) Tue Oct 27 12:07:33 2009
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
SOURCES += drückmich.cpp
